### ISSUE TITLE
Some UI Texts are not being shown in MacOS

### ISSUE THREAD

**Issue by kuruk-mm** [decentraland/explorer-desktop#287] opened 2022-05-04 14:25 UTC
<img width="889" alt="image" src="https://user-images.githubusercontent.com/12563266/166702374-7e7de3b0-623a-4e30-bb74-1aa4aed0afc4.png">

This was reproduced in Intel Macbook Pro and Macbook M1.

Also, for example in the ICE Poker scenes, some UI Texts work while others don't:

<img width="1535" alt="Screen Shot 2022-05-07 at 02 23 10" src="https://user-images.githubusercontent.com/1031741/167241041-b5052f2b-f149-46a6-a744-4edfdf7761ec.png">

**Comment by davidejensen** [comment] 2022-05-13 09:17
Blocked for the moment, will wait for the CJK character issue to avoid conflicts and solve it then.

The problem is related to how the default font material is generated, the original font is required to display the text in every scenario

**Comment by davidejensen** [comment] 2022-05-23 09:50
Interesting info: https://forum.unity.com/threads/text-missing-on-apple-m1-mac-builds.1021987/

**Comment by Kinerius** [comment] 2022-05-23 19:50
Did a bit of research on this topic, in the forum post that @davidejensen mentioned, the unity team managed to fix this by updating the version of TextMeshPro, sadly this version is not compatible with our unity version and we might want to wait for https://github.com/decentraland/unity-renderer/issues/1797 or we can go for the approach that is mentioned on that post, that is separating the materials from UI and 3D texts.

**Comment by Kinerius** [comment] 2022-05-24 21:09
Update: After updating to Unity 2020.3.34f1 the problem seems to be solved, but we started having some visual artifacts regarding the SSAO on avatars.
This issue was fixed by downgrading URP a few versions but this introduced the text problem again in Desktop.

**Closed** 2022-06-23 18:09 UTC
Labels: bug, confirmed
