### ISSUE TITLE
Video streaming clickable texture has problems in Desktop client

### ISSUE THREAD

**Issue by Suduck** [decentraland/explorer-desktop#81] opened 2022-01-28 17:49 UTC
### What happened?

In the scene -28, 68 the DCL Cinema has a screen with a movie that doesn't work in desktop

### Steps to reproduce

Go to -28,68 
Enter the cinema
See the screen

### Operating System

Windwos 10

### Wallet

Metamask

### CPU

ddd

### GPU

ddd

### RAM

32 gb

### Kernel Version

ultima

### Unity Version

ultima

**Comment by kuruk-mm** [comment] 2022-02-18 23:06
The video is loading well. The problem is the texture of the screen with the "Play Video", for some reason it's not been shown.

**Comment by Kinerius** [comment] 2022-05-12 20:38
The streaming is working and the "Play Video" appears sometimes, but the video itself its not showing up, something is wrong with the conversion.

[Tested with M1]

**Comment by Kinerius** [comment] 2022-05-17 12:59
I can confirm that the clickable texture is working, the video not showing up might be a format problem that may be resolved with #2196

**Closed by Kinerius** 2022-05-17 12:59 UTC
Labels: bug, confirmed
