### ISSUE TITLE
Fix white texture in the middle of the screen

### ISSUE THREAD

**Issue by Cooper8555** [decentraland/explorer-desktop#359] opened 2022-07-18 23:30 UTC
### What happened?

![unknown_2022 07 19-02 19](https://user-images.githubusercontent.com/109559909/179632876-71b38a6d-3162-48f0-a98e-2cbddbc8cb3b.png)

It happened in  Wilderness.  I wanted to play with  NPC  but when pressed on the entrance a white square appeared and does not disappear 

### Steps to reproduce

go to the game with  NPC  and click on the entrance and that's it 

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 7 2700 Eight-Core Processor 

### GPU

Radeon RX 580 Series 8170MB

### RAM

16334MB

### Kernel Version

1.0.0-2673696742.commit-535b3fa

### Unity Version

desktop-1.0.481-20220714181434.commit-d37208d

### Realm

dg

### NameTag

Cooper#8a81

### Acceptance Criteria
- [ ] No white texture shown

**Comment by Cooper8555** [comment] 2022-07-21 21:31
> If you get out of that scene, does the white square disappear?

no will not disappear ,  only if you completely exit the game

**Comment by dalkia** [comment] 2022-08-30 20:03
Hello @Cooper8555! 

I gave a look at the issue, but it seems that portals are no longer accessible by clicking on them. Now you access them by going through them directly.

I was not able to reproduce the error and get the white square. Is this still happening to you?

**Comment by Cooper8555** [comment] 2022-08-30 20:10
no, it's all good


вт, 30 авг. 2022 г., 23:03 Juan Ignacio Molteni ***@***.***>:

**Comment by dalkia** [comment] 2022-08-30 20:21
Great, closing this issue. Thank you for your support!

**Closed** 2022-08-30 20:21 UTC
Labels: explorer-desktop
